imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@KupelikeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    directorio_kupelas: '%kernel.root_dir%/../web/uploads/kupelas'
    directorio_sagardotegis: '%kernel.root_dir%/../web/uploads/sagardotegis'

framework:
    #esi:             ~
    translator:      
        fallback: ["%locale%"] 
        #paths:
        #    - '@KupelikeBundle/Resources/translations'
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        #driver:   "%database_driver%"
        #host:     "%database_host%"
        #port:     "%database_port%"
        #dbname:   "%database_name%"
        #user:     "%database_user%"
        #password: "%database_password%"
        charset:  UTF8
        # unix_socket: "/tmp/mysql.sock"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  gmail
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    #port:       465
    username:  "%mail_username%"
    password:  "%mail_password%"
    
    


# app/config/config.yml
lopi_pusher:
    app_id: "%pusher_id%"
    key: "%pusher_key%"
    secret: "%pusher_secret%"
    #app_id: "%pusher.app_id%"
    #key: "%pusher.app_key%"
    #secret: "%pusher.app_secret%"

    # Default configuration
    #debug: false # true if you want use the debug of all requests
    #cluster: "eu" # Change the cluster name
    #host: http://api.pusherapp.com
    #port: 443
    #timeout: 30

    # optional if you want to use private or presence channels
    # see the section about "Private and Presense channel auth" below
    # auth_service_id: <the_auth_service_id>
  
    
hwi_oauth:
    firewall_names:        [secured_area]
    resource_owners:
        facebook:
            type:          facebook
            client_id:     "%facebook_id%"
            client_secret: "%facebook_secret%"
            infos_url:     "https://graph.facebook.com/me?fields=username,name,picture.type(square)"
            scope:         "email"
            options:
                display: popup 

services:
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider