# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        KupelikeBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12
        
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: KupelikeBundle:Usuario
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login: 
                login_path: /es/login
                check_path: /es/login_check
                username_parameter: _username
                password_parameter: _password
                
                always_use_default_target_path: true
                default_target_path: /es/index
            logout:
              path: /logout
              target: /es/index
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        
        secured_area:
            pattern:    ^/login
            oauth:
                resource_owners:
                    facebook:      /login_facebook
                login_path:        /demo/secured/login
                failure_path:      /demo/secured/login
                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity
    
            # Turn on anonymous for testings need.
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios, roles: [ROLE_SIDRERO, ROLE_ADMIN] }
        - { path: ^/nuevo-usuario, roles: ROLE_ADMIN }
        - { path: ^/panel-usuarios, roles: ROLE_ADMIN }
        - { path: ^/registrar-usuario, roles: ROLE_ADMIN }
        - { path: ^/usuarios/lista, roles: ROLE_ADMIN }
        - { path: ^/usuarios, roles: ROLE_ADMIN }
        - { path: ^/usuario/nuevo, roles: ROLE_ADMIN }
        - { path: ^/sidreria, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/kupelas/lista, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/kupelas/nuevo, roles: IS_AUTHENTICATED_FULLY }
        #es
        - { path: ^/es/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/es/usuarios, roles: [ROLE_SIDRERO, ROLE_ADMIN] }
        - { path: ^/es/nuevo-usuario, roles: ROLE_ADMIN }
        - { path: ^/es/panel-usuarios, roles: ROLE_ADMIN }
        - { path: ^/es/registrar-usuario, roles: ROLE_ADMIN }
        - { path: ^/es/usuarios/lista, roles: ROLE_ADMIN }
        - { path: ^/es/usuarios, roles: ROLE_ADMIN }
        - { path: ^/es/usuario/nuevo, roles: ROLE_ADMIN }
        - { path: ^/es/sidreria, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/es/kupelas/lista, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/es/kupelas/nuevo, roles: IS_AUTHENTICATED_FULLY }
        #en
        - { path: ^/en/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/usuarios, roles: [ROLE_SIDRERO, ROLE_ADMIN] }
        - { path: ^/en/nuevo-usuario, roles: ROLE_ADMIN }
        - { path: ^/en/panel-usuarios, roles: ROLE_ADMIN }
        - { path: ^/en/registrar-usuario, roles: ROLE_ADMIN }
        - { path: ^/en/usuarios/lista, roles: ROLE_ADMIN }
        - { path: ^/en/usuarios, roles: ROLE_ADMIN }
        - { path: ^/en/usuario/nuevo, roles: ROLE_ADMIN }
        - { path: ^/en/sidreria, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/kupelas/lista, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/kupelas/nuevo, roles: IS_AUTHENTICATED_FULLY }
        #eus
        - { path: ^/eus/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/eus/usuarios, roles: [ROLE_SIDRERO, ROLE_ADMIN] }
        - { path: ^/eus/nuevo-usuario, roles: ROLE_ADMIN }
        - { path: ^/eus/panel-usuarios, roles: ROLE_ADMIN }
        - { path: ^/eus/registrar-usuario, roles: ROLE_ADMIN }
        - { path: ^/eus/usuarios/lista, roles: ROLE_ADMIN }
        - { path: ^/eus/usuarios, roles: ROLE_ADMIN }
        - { path: ^/eus/usuario/nuevo, roles: ROLE_ADMIN }
        - { path: ^/eus/sidreria, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/eus/kupelas/lista, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/eus/kupelas/nuevo, roles: IS_AUTHENTICATED_FULLY }