<?php

namespace KupelikeBundle\Repository;

/**
 * horarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class horarioRepository extends \Doctrine\ORM\EntityRepository
{
}
