<?php

namespace KupelikeBundle\Repository;

/**
 * KupelaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KupelaRepository extends \Doctrine\ORM\EntityRepository
{
}
