<?php

namespace KupelikeBundle\Repository;

/**
 * SagardotegiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SagardotegiRepository extends \Doctrine\ORM\EntityRepository
{
}
