<?php

namespace KupelikeBundle\Repository;

/**
 * VotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotoRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function sumKupelas(){
        return $this->getEntityManager()->createQuery('SELECT count(u.id) FROM KupelikeBundle:Voto u, KupelikeBundle:Kupela a  
                WHERE a.id = u.kupelaId')
                ->getResult();
    }*/
}
