<?php

namespace KupelikeBundle\Repository;

/**
 * VotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotoRepository extends \Doctrine\ORM\EntityRepository
{
}
