index:
    path: /
    defaults: { _controller: KupelikeBundle:Index:index }
    
Sagardotegis_index:
    path: /sagardotegiak
    defaults: { _controller: KupelikeBundle:Sagardotegi:lista }
    
kupelak_index:
    path: /sagardotegiak/{idSagardotegi}
    defaults: { _controller: KupelikeBundle:Sagardotegi:view }