index:
    path: /
    defaults: { _controller: KupelikeBundle:Index:index }
    
sagardotegis_index:
    path: /sagardotegiak
    defaults: { _controller: KupelikeBundle:Sagardotegi:lista }
    methods: [GET]
    
sagardotegi_view:
    path: /sagardotegiak/{idSagardotegi}
    defaults: { _controller: KupelikeBundle:Sagardotegi:view }
    methods: [GET]
    
sagardotegi_mapa:
    path: /sagardotegiak/{idSagardotegi}/mapa
    defaults: { _controller: KupelikeBundle:Sagardotegi:mapa }
    methods: [GET]
    
sagardotegien_mapak:
    path: /mapak
    defaults: { _controller: KupelikeBundle:Sagardotegi:mapak }
    methods: [GET]
    
gps:
    path: /gps
    defaults: { _controller: KupelikeBundle:Sagardotegi:gps }
    methods: [GET]
    
contacto:
    path: /contacto
    defaults: { _controller: KupelikeBundle:Index:contacto }
    methods: [GET]
    
nosotros:
    path: /nosotros
    defaults: { _controller: KupelikeBundle:Index:nosotros }
    methods: [GET]    

kupela_like:
    path: /kupela-like
    defaults: { _controller: KupelikeBundle:Kupela:like }
    methods: [POST]
    
# API REST URL

obtener_kupelas:
    path: /api/get-kupelas/{idPagina}
    defaults: { _controller: KupelikeBundle:Sagardotegi:getKupelas }
    methods: [GET]
    
obtener_likes:
    path: /api/get-likes/{idKupela}
    defaults: { _controller: KupelikeBundle:Sagardotegi:getLikes }
    methods: [GET]